services:
  node-a:
    build: .
    container_name: node-a
    environment:
      - NODE_ID=node-a
      - NODE_IDS=node-a,node-b,node-c
    ports:
      - "8081:8080"

  node-b:
    build: .
    container_name: node-b
    environment:
      - NODE_ID=node-b
      - NODE_IDS=node-a,node-b,node-c
    ports:
      - "8082:8080"

  node-c:
    build: .
    container_name: node-c
    environment:
      - NODE_ID=node-c
      - NODE_IDS=node-a,node-b,node-c
    ports:
      - "8083:8080"
